services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASEURL: https://api-olt.abanetlink.id
    image: onu-monitor:latest
    container_name: onu-monitor
    environment:
      - NEXT_PUBLIC_BASEURL=https://api-olt.abanetlink.id
    ports:
      - "4099:3000"